// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KLineHeader: typeof import('./src/components/KLineHeader.vue')['default']
    KLineWidget: typeof import('./src/components/KLineWidget.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
